### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by 1632325673** [XAIMI-Lab/McMRSR#1]
Hello, I used the public dataset fastmri for training. The following error occurred. The dataset is：
knee_singlecoil_val.tar
knee_singlecoil_test_v2.tar
knee_singlecoil_train.tar
What does the keyword T2 stand for

Traceback (most recent call last):
  File "train_demo.py", line 136, in <module>
    for it, data in enumerate(train_bar):
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/qfl/YES/envs/McMRSR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/qfl/McMRSR/datasets/cartesian_dataset.py", line 37, in __getitem__
    T2_256_img_real = T2_img['T2'].real
KeyError: 'T2'

**Comment by mylyu** [comment]
Same problem. The current code cannot run on the public fastMRI knee dataset. Since it is a CVPR paper, can the authors revise the code to keep the high standard? Thanks.
